<link rel="stylesheet" href="{{ asset('frontend/assets/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/price_rangs.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/slicknav.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/fontawesome-all.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/themify-icons.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/slick.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/style.css') }}">
